<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="8.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.21.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Api\HackerNews.BestStories.Api\HackerNews.BestStories.Api.csproj" />
    <ProjectReference Include="..\..\src\Application\HackerNews.BestStories.Application\HackerNews.BestStories.Application.csproj" />
    <ProjectReference Include="..\..\src\Domain\HackerNews.BestStories.Domain\HackerNews.BestStories.Domain.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\HackerNews.BestStories.Infrastructure\HackerNews.BestStories.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>